# Generated by Django 5.2.7 on 2025-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='user@django.com', max_length=100)),
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('pic', models.FileField(upload_to='profile')),
            ],
        ),
    ]
